"""
UML Forge Connector — API Client

Thin HTTP client for the UML Forge hosted API.
ZERO business logic. ZERO prompt text.
All diagram generation happens server-side.
"""

from __future__ import annotations

import httpx

from connector.config import load_config

# Timeout for diagram generation — Anthropic calls can take up to ~60s
_GENERATE_TIMEOUT = 210.0
_SUGGEST_TIMEOUT  = 30.0


async def generate(
    tool: str,
    params: dict,
    guided_mode: bool = False,
) -> str:
    """
    Call POST /v1/generate on the UML Forge API.
    Returns a formatted Markdown string ready for display in a coding agent.
    """
    config = load_config()

    async with httpx.AsyncClient(timeout=_GENERATE_TIMEOUT) as client:
        response = await client.post(
            f"{config.api_base_url}/v1/generate",
            json={
                "tool": tool,
                "params": params,
                "guided_mode": guided_mode and config.guided_mode,
            },
            headers={
                "Authorization": f"Bearer {config.api_key}",
                "Content-Type": "application/json",
            },
        )

    if response.status_code == 402:
        body = response.json()
        upgrade_url = body.get("upgrade_url", "https://umlforge.dev/billing")
        return (
            f"**Monthly diagram limit reached.**\n\n"
            f"{body.get('error', 'Upgrade to Pro for unlimited diagrams.')}\n\n"
            f"Upgrade at: {upgrade_url}"
        )

    if response.status_code == 401:
        return (
            "**Authentication failed.** Check that your API key in "
            "your UMLFORGE_API_KEY is correct and active."
        )

    response.raise_for_status()
    return _format_generate_response(response.json())


async def suggest(task_description: str) -> str:
    """
    Call POST /v1/suggest on the UML Forge API.
    Returns a formatted recommendation string.
    """
    config = load_config()

    async with httpx.AsyncClient(timeout=_SUGGEST_TIMEOUT) as client:
        response = await client.post(
            f"{config.api_base_url}/v1/suggest",
            json={"task_description": task_description},
            headers={
                "Authorization": f"Bearer {config.api_key}",
                "Content-Type": "application/json",
            },
        )

    if response.status_code == 401:
        return (
            "**Authentication failed.** Check that your API key in "
            "your UMLFORGE_API_KEY is correct and active."
        )

    if response.status_code == 402:
        body = response.json()
        upgrade_url = body.get("upgrade_url", "https://umlforge.dev/billing")
        return (
            f"**Monthly diagram limit reached.**\n\n"
            f"{body.get('error', 'Upgrade to Pro for unlimited diagrams.')}\n\n"
            f"Upgrade at: {upgrade_url}"
        )

    response.raise_for_status()
    body = response.json()

    return (
        f"**Recommended tool:** `{body['recommended_tool']}`\n\n"
        f"{body['reasoning']}\n\n"
        f"**Alternative:** `{body['alternative_tool']}`  \n"
        f"{body['alternative_reasoning']}\n\n"
        f"*Call the recommended tool with your task details to generate the diagram.*"
    )


# ── Response formatter ────────────────────────────────────────────────────────

def _format_generate_response(body: dict) -> str:
    """
    Format a /v1/generate response body into readable Markdown.

    Output shape:
      ## Diagram Title [⚠️ if validation warning]

      ```mermaid
      [content]
      ```

      [supplementary tables / notes]

      ---
      *Generated by UML Forge | X diagrams remaining this month*
    """
    parts: list[str] = []

    for diagram in body.get("diagrams", []):
        title   = diagram.get("title", "Diagram")
        mermaid = diagram.get("mermaid", "").strip()
        warning = " ⚠️ _validation warning — review before using_" \
                  if diagram.get("validation_warning") else ""

        parts.append(f"## {title}{warning}\n\n```mermaid\n{mermaid}\n```")

    # Supplementary sections (STRIDE table, implementation notes, etc.)
    supplementary = body.get("supplementary", {})
    for key, content in supplementary.items():
        if isinstance(content, str) and content.strip():
            parts.append(content.strip())

    # Usage footer
    usage     = body.get("usage", {})
    remaining = usage.get("diagrams_remaining")
    tier      = usage.get("tier", "free")

    if remaining is not None:
        footer = f"*Generated by UML Forge | {remaining} diagrams remaining this month*"
    else:
        footer = f"*Generated by UML Forge | {tier.title()} — unlimited diagrams*"

    parts.append("---\n" + footer)

    return "\n\n".join(parts)
